# Generated by Django 5.1 on 2025-12-04 23:34

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import taggit.managers
import wagtail.blocks
import wagtail.contrib.forms.models
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.images.models
import wagtail.models.collections
import wagtail.search.index
import wagtail.snippets.blocks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Index des articles',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('couleur', models.CharField(default='#1E40AF', max_length=7)),
            ],
            options={
                'verbose_name': "Catégorie d'article",
                'verbose_name_plural': "Catégories d'articles",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('horaires', wagtail.fields.RichTextField(blank=True)),
                ('message_confirmation', models.TextField(default='Votre message a bien été envoyé. Nous vous répondrons dans les plus brefs délais.')),
                ('contenu', wagtail.fields.StreamField([('texte_riche', wagtail.blocks.StructBlock([('contenu', wagtail.blocks.RichTextBlock()), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('1', '1 colonne (pleine largeur)'), ('2', '2 colonnes')]))])), ('contact', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(default='Nous contacter', required=False)), ('adresse', wagtail.blocks.TextBlock(required=False)), ('telephone', wagtail.blocks.CharBlock(required=False)), ('email', wagtail.blocks.EmailBlock(required=False)), ('horaires', wagtail.blocks.RichTextBlock(required=False)), ('afficher_formulaire', wagtail.blocks.BooleanBlock(default=False, required=False))])), ('carte', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('latitude', wagtail.blocks.FloatBlock(required=True)), ('longitude', wagtail.blocks.FloatBlock(required=True)), ('zoom', wagtail.blocks.IntegerBlock(default=15, max_value=20, min_value=1)), ('hauteur', wagtail.blocks.IntegerBlock(default=400, help_text='Hauteur en pixels')), ('marqueur_titre', wagtail.blocks.CharBlock(required=False))]))], blank=True)),
            ],
            options={
                'verbose_name': 'Page contact',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EvenementIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Index des événements',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('reponse', wagtail.fields.RichTextField()),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('publie', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='FormulaireContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('remerciement', wagtail.fields.RichTextField(blank=True, verbose_name='Message de remerciement')),
            ],
            options={
                'verbose_name': 'Formulaire de contact',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='MenuPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Menu principal',
                'verbose_name_plural': 'Menus principaux',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProjetIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Index des projets',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DocumentPersonnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='documents', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('categorie', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('date_document', models.DateField(blank=True, null=True, verbose_name='Date du document')),
                ('collection', models.ForeignKey(default=wagtail.models.collections.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ChampFormulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='cms.formulairecontactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagePersonnalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width')),
                ('width', models.IntegerField(editable=False, verbose_name='width')),
                ('height', models.IntegerField(editable=False, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=40)),
                ('legende', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('credit', models.CharField(blank=True, max_length=255, verbose_name='Crédit photo')),
                ('collection', models.ForeignKey(default=wagtail.models.collections.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
            bases=(wagtail.images.models.ImageFileMixin, wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='EvenementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('lieu', models.CharField(max_length=300)),
                ('adresse', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', wagtail.fields.RichTextField()),
                ('organisateur', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_telephone', models.CharField(blank=True, max_length=50)),
                ('gratuit', models.BooleanField(default=True)),
                ('prix', models.CharField(blank=True, max_length=100)),
                ('lien_inscription', models.URLField(blank=True)),
                ('image_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EquipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('contenu', wagtail.fields.StreamField([('texte_riche', wagtail.blocks.StructBlock([('contenu', wagtail.blocks.RichTextBlock()), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('1', '1 colonne (pleine largeur)'), ('2', '2 colonnes')]))])), ('equipe', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('sous_titre', wagtail.blocks.TextBlock(required=False)), ('membres', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('membre', wagtail.snippets.blocks.SnippetChooserBlock('cms.MembreEquipe'))]))), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('3', '3 colonnes'), ('4', '4 colonnes')]))]))], blank=True)),
                ('image_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee')),
            ],
            options={
                'verbose_name': 'Page équipe',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ConfigurationMairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mairie', models.CharField(max_length=200, verbose_name='Nom de la mairie')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Slogan')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('horaires', wagtail.fields.RichTextField(blank=True, verbose_name="Horaires d'ouverture")),
                ('couleur_primaire', models.CharField(default='#1E40AF', help_text='Code hexadécimal (ex: #1E40AF)', max_length=7, verbose_name='Couleur primaire')),
                ('couleur_secondaire', models.CharField(default='#059669', max_length=7, verbose_name='Couleur secondaire')),
                ('couleur_accent', models.CharField(default='#F59E0B', max_length=7, verbose_name="Couleur d'accent")),
                ('meta_description', models.TextField(blank=True, help_text='Description pour les moteurs de recherche', verbose_name='Description SEO')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='ID Google Analytics')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee', verbose_name='Favicon')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Configuration de la mairie',
            },
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('resume', models.TextField(max_length=500, verbose_name='Résumé')),
                ('contenu', wagtail.fields.StreamField([('texte_riche', wagtail.blocks.StructBlock([('contenu', wagtail.blocks.RichTextBlock()), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('1', '1 colonne (pleine largeur)'), ('2', '2 colonnes')]))])), ('texte_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('titre', wagtail.blocks.CharBlock(required=False)), ('texte', wagtail.blocks.RichTextBlock()), ('position_image', wagtail.blocks.ChoiceBlock(choices=[('left', 'Image à gauche'), ('right', 'Image à droite')])), ('ratio', wagtail.blocks.ChoiceBlock(choices=[('50-50', '50% - 50%'), ('40-60', '40% - 60%'), ('60-40', '60% - 40%')]))])), ('galerie', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('legende', wagtail.blocks.CharBlock(required=False))]))), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('2', '2 colonnes'), ('3', '3 colonnes'), ('4', '4 colonnes')])), ('lightbox', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('video', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock()), ('description', wagtail.blocks.TextBlock(required=False))])), ('citation', wagtail.blocks.StructBlock([('contenu', wagtail.blocks.RichTextBlock()), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('1', '1 colonne (pleine largeur)'), ('2', '2 colonnes')]))])), ('documents', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('documents', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('titre_personnalise', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.TextBlock(required=False))]))), ('affichage', wagtail.blocks.ChoiceBlock(choices=[('liste', 'Liste'), ('grille', 'Grille'), ('tableau', 'Tableau')]))]))])),
                ('vues', models.PositiveIntegerField(default=0)),
                ('seo_titre', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.TextField(blank=True, max_length=160)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_wagtail', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='cms.categoriearticle')),
                ('image_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee', verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('fonction', models.CharField(max_length=200)),
                ('biographie', wagtail.fields.RichTextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('lien_externe', models.URLField(blank=True, verbose_name='Lien externe')),
                ('ouvrir_nouvel_onglet', models.BooleanField(default=False)),
                ('lien_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page interne')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menuprincipal')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageAccueil',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_titre', models.CharField(max_length=300, verbose_name='Titre du hero')),
                ('hero_sous_titre', models.TextField(blank=True, verbose_name='Sous-titre')),
                ('hero_bouton_texte', models.CharField(blank=True, default='Découvrir', max_length=50)),
                ('contenu', wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(max_length=200, required=True)), ('sous_titre', wagtail.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video_url', wagtail.blocks.URLBlock(help_text='URL YouTube ou Vimeo', required=False)), ('overlay', wagtail.blocks.BooleanBlock(default=True, help_text='Ajouter un overlay sombre', required=False)), ('boutons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('texte', wagtail.blocks.CharBlock(required=True)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('url_externe', wagtail.blocks.URLBlock(required=False)), ('style', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primaire'), ('secondary', 'Secondaire'), ('outline', 'Contour'), ('ghost', 'Transparent')]))]), max_num=2)), ('hauteur', wagtail.blocks.ChoiceBlock(choices=[('small', 'Petite (400px)'), ('medium', 'Moyenne (500px)'), ('large', 'Grande (600px)'), ('full', 'Plein écran')]))])), ('services', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('sous_titre', wagtail.blocks.TextBlock(required=False)), ('services', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('service', wagtail.snippets.blocks.SnippetChooserBlock('cms.ServiceMairie'))]))), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('2', '2 colonnes'), ('3', '3 colonnes'), ('4', '4 colonnes')]))])), ('actualites', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('sous_titre', wagtail.blocks.TextBlock(required=False)), ('cartes', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('lien', wagtail.blocks.PageChooserBlock(required=False)), ('url_externe', wagtail.blocks.URLBlock(required=False)), ('icone', wagtail.blocks.CharBlock(help_text="Nom de l'icône", required=False))]))), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('2', '2 colonnes'), ('3', '3 colonnes'), ('4', '4 colonnes')]))])), ('statistiques', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('sous_titre', wagtail.blocks.TextBlock(required=False)), ('statistiques', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('valeur', wagtail.blocks.CharBlock(help_text='Ex: 10000, 95%', required=True)), ('label', wagtail.blocks.CharBlock(required=True)), ('icone', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.TextBlock(required=False))]))), ('style', wagtail.blocks.ChoiceBlock(choices=[('light', 'Fond clair'), ('dark', 'Fond sombre'), ('primary', 'Fond primaire')]))])), ('equipe', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('sous_titre', wagtail.blocks.TextBlock(required=False)), ('membres', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('membre', wagtail.snippets.blocks.SnippetChooserBlock('cms.MembreEquipe'))]))), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('3', '3 colonnes'), ('4', '4 colonnes')]))])), ('temoignages', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('temoignages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('temoignage', wagtail.snippets.blocks.SnippetChooserBlock('cms.Temoignage'))]))), ('carrousel', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('cta', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('image_fond', wagtail.images.blocks.ImageChooserBlock(required=False)), ('bouton', wagtail.blocks.StructBlock([('texte', wagtail.blocks.CharBlock(required=True)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('url_externe', wagtail.blocks.URLBlock(required=False)), ('style', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primaire'), ('secondary', 'Secondaire'), ('outline', 'Contour'), ('ghost', 'Transparent')]))])), ('style', wagtail.blocks.ChoiceBlock(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('primary', 'Couleur primaire'), ('gradient', 'Dégradé')]))])), ('galerie', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('legende', wagtail.blocks.CharBlock(required=False))]))), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('2', '2 colonnes'), ('3', '3 colonnes'), ('4', '4 colonnes')])), ('lightbox', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('texte_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('titre', wagtail.blocks.CharBlock(required=False)), ('texte', wagtail.blocks.RichTextBlock()), ('position_image', wagtail.blocks.ChoiceBlock(choices=[('left', 'Image à gauche'), ('right', 'Image à droite')])), ('ratio', wagtail.blocks.ChoiceBlock(choices=[('50-50', '50% - 50%'), ('40-60', '40% - 60%'), ('60-40', '60% - 40%')]))])), ('video', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock()), ('description', wagtail.blocks.TextBlock(required=False))])), ('faq', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('elements', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=True)), ('contenu', wagtail.blocks.RichTextBlock(required=True)), ('ouvert', wagtail.blocks.BooleanBlock(default=False, required=False))])))])), ('timeline', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('elements', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('date', wagtail.blocks.CharBlock(required=True)), ('titre', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('contact', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(default='Nous contacter', required=False)), ('adresse', wagtail.blocks.TextBlock(required=False)), ('telephone', wagtail.blocks.CharBlock(required=False)), ('email', wagtail.blocks.EmailBlock(required=False)), ('horaires', wagtail.blocks.RichTextBlock(required=False)), ('afficher_formulaire', wagtail.blocks.BooleanBlock(default=False, required=False))])), ('carte', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('latitude', wagtail.blocks.FloatBlock(required=True)), ('longitude', wagtail.blocks.FloatBlock(required=True)), ('zoom', wagtail.blocks.IntegerBlock(default=15, max_value=20, min_value=1)), ('hauteur', wagtail.blocks.IntegerBlock(default=400, help_text='Hauteur en pixels')), ('marqueur_titre', wagtail.blocks.CharBlock(required=False))])), ('documents', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('documents', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('titre_personnalise', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.TextBlock(required=False))]))), ('affichage', wagtail.blocks.ChoiceBlock(choices=[('liste', 'Liste'), ('grille', 'Grille'), ('tableau', 'Tableau')]))])), ('texte_riche', wagtail.blocks.StructBlock([('contenu', wagtail.blocks.RichTextBlock()), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('1', '1 colonne (pleine largeur)'), ('2', '2 colonnes')]))]))], blank=True, verbose_name='Contenu de la page')),
                ('seo_titre', models.CharField(blank=True, max_length=70, verbose_name='Titre SEO')),
                ('seo_description', models.TextField(blank=True, max_length=160, verbose_name='Description SEO')),
                ('hero_bouton_lien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Lien du bouton')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee', verbose_name='Image de fond')),
            ],
            options={
                'verbose_name': "Page d'accueil",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PageStandard',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('contenu', wagtail.fields.StreamField([('texte_riche', wagtail.blocks.StructBlock([('contenu', wagtail.blocks.RichTextBlock()), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('1', '1 colonne (pleine largeur)'), ('2', '2 colonnes')]))])), ('texte_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('titre', wagtail.blocks.CharBlock(required=False)), ('texte', wagtail.blocks.RichTextBlock()), ('position_image', wagtail.blocks.ChoiceBlock(choices=[('left', 'Image à gauche'), ('right', 'Image à droite')])), ('ratio', wagtail.blocks.ChoiceBlock(choices=[('50-50', '50% - 50%'), ('40-60', '40% - 60%'), ('60-40', '60% - 40%')]))])), ('galerie', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('legende', wagtail.blocks.CharBlock(required=False))]))), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('2', '2 colonnes'), ('3', '3 colonnes'), ('4', '4 colonnes')])), ('lightbox', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('video', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock()), ('description', wagtail.blocks.TextBlock(required=False))])), ('accordion', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('elements', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=True)), ('contenu', wagtail.blocks.RichTextBlock(required=True)), ('ouvert', wagtail.blocks.BooleanBlock(default=False, required=False))])))])), ('cta', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('image_fond', wagtail.images.blocks.ImageChooserBlock(required=False)), ('bouton', wagtail.blocks.StructBlock([('texte', wagtail.blocks.CharBlock(required=True)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('url_externe', wagtail.blocks.URLBlock(required=False)), ('style', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primaire'), ('secondary', 'Secondaire'), ('outline', 'Contour'), ('ghost', 'Transparent')]))])), ('style', wagtail.blocks.ChoiceBlock(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('primary', 'Couleur primaire'), ('gradient', 'Dégradé')]))])), ('documents', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('documents', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('titre_personnalise', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.TextBlock(required=False))]))), ('affichage', wagtail.blocks.ChoiceBlock(choices=[('liste', 'Liste'), ('grille', 'Grille'), ('tableau', 'Tableau')]))])), ('contact', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(default='Nous contacter', required=False)), ('adresse', wagtail.blocks.TextBlock(required=False)), ('telephone', wagtail.blocks.CharBlock(required=False)), ('email', wagtail.blocks.EmailBlock(required=False)), ('horaires', wagtail.blocks.RichTextBlock(required=False)), ('afficher_formulaire', wagtail.blocks.BooleanBlock(default=False, required=False))])), ('carte', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('latitude', wagtail.blocks.FloatBlock(required=True)), ('longitude', wagtail.blocks.FloatBlock(required=True)), ('zoom', wagtail.blocks.IntegerBlock(default=15, max_value=20, min_value=1)), ('hauteur', wagtail.blocks.IntegerBlock(default=400, help_text='Hauteur en pixels')), ('marqueur_titre', wagtail.blocks.CharBlock(required=False))])), ('statistiques', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('sous_titre', wagtail.blocks.TextBlock(required=False)), ('statistiques', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('valeur', wagtail.blocks.CharBlock(help_text='Ex: 10000, 95%', required=True)), ('label', wagtail.blocks.CharBlock(required=True)), ('icone', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.TextBlock(required=False))]))), ('style', wagtail.blocks.ChoiceBlock(choices=[('light', 'Fond clair'), ('dark', 'Fond sombre'), ('primary', 'Fond primaire')]))])), ('equipe', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('sous_titre', wagtail.blocks.TextBlock(required=False)), ('membres', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('membre', wagtail.snippets.blocks.SnippetChooserBlock('cms.MembreEquipe'))]))), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('3', '3 colonnes'), ('4', '4 colonnes')]))]))], blank=True)),
                ('seo_titre', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.TextField(blank=True, max_length=160)),
                ('image_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee', verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Page standard',
                'verbose_name_plural': 'Pages standard',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.PageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('site_web', models.URLField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cms.imagepersonnalisee')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProjetPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('pourcentage_avancement', models.PositiveIntegerField(default=0)),
                ('description', wagtail.fields.RichTextField()),
                ('objectifs', wagtail.fields.RichTextField(blank=True)),
                ('budget_alloue', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('budget_execute', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('partenaires', models.TextField(blank=True)),
                ('contenu', wagtail.fields.StreamField([('texte_riche', wagtail.blocks.StructBlock([('contenu', wagtail.blocks.RichTextBlock()), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('1', '1 colonne (pleine largeur)'), ('2', '2 colonnes')]))])), ('texte_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('titre', wagtail.blocks.CharBlock(required=False)), ('texte', wagtail.blocks.RichTextBlock()), ('position_image', wagtail.blocks.ChoiceBlock(choices=[('left', 'Image à gauche'), ('right', 'Image à droite')])), ('ratio', wagtail.blocks.ChoiceBlock(choices=[('50-50', '50% - 50%'), ('40-60', '40% - 60%'), ('60-40', '60% - 40%')]))])), ('galerie', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('legende', wagtail.blocks.CharBlock(required=False))]))), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('2', '2 colonnes'), ('3', '3 colonnes'), ('4', '4 colonnes')])), ('lightbox', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('video', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock()), ('description', wagtail.blocks.TextBlock(required=False))])), ('timeline', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('elements', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('date', wagtail.blocks.CharBlock(required=True)), ('titre', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('documents', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('documents', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('titre_personnalise', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.TextBlock(required=False))]))), ('affichage', wagtail.blocks.ChoiceBlock(choices=[('liste', 'Liste'), ('grille', 'Grille'), ('tableau', 'Tableau')]))]))], blank=True)),
                ('image_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee')),
            ],
            options={
                'verbose_name': 'Projet municipal',
                'verbose_name_plural': 'Projets municipaux',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceMairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: users, file-text, calendar)", max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('lien_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page de détail')),
            ],
            options={
                'verbose_name': 'Service de la mairie',
                'verbose_name_plural': 'Services de la mairie',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('introduction', wagtail.fields.RichTextField()),
                ('contenu', wagtail.fields.StreamField([('texte_riche', wagtail.blocks.StructBlock([('contenu', wagtail.blocks.RichTextBlock()), ('colonnes', wagtail.blocks.ChoiceBlock(choices=[('1', '1 colonne (pleine largeur)'), ('2', '2 colonnes')]))])), ('texte_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('titre', wagtail.blocks.CharBlock(required=False)), ('texte', wagtail.blocks.RichTextBlock()), ('position_image', wagtail.blocks.ChoiceBlock(choices=[('left', 'Image à gauche'), ('right', 'Image à droite')])), ('ratio', wagtail.blocks.ChoiceBlock(choices=[('50-50', '50% - 50%'), ('40-60', '40% - 60%'), ('60-40', '60% - 40%')]))])), ('accordion', wagtail.blocks.StructBlock([('titre_section', wagtail.blocks.CharBlock(required=False)), ('elements', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=True)), ('contenu', wagtail.blocks.RichTextBlock(required=True)), ('ouvert', wagtail.blocks.BooleanBlock(default=False, required=False))])))])), ('documents', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=False)), ('documents', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('titre_personnalise', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.TextBlock(required=False))]))), ('affichage', wagtail.blocks.ChoiceBlock(choices=[('liste', 'Liste'), ('grille', 'Grille'), ('tableau', 'Tableau')]))])), ('contact', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(default='Nous contacter', required=False)), ('adresse', wagtail.blocks.TextBlock(required=False)), ('telephone', wagtail.blocks.CharBlock(required=False)), ('email', wagtail.blocks.EmailBlock(required=False)), ('horaires', wagtail.blocks.RichTextBlock(required=False)), ('afficher_formulaire', wagtail.blocks.BooleanBlock(default=False, required=False))])), ('cta', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('image_fond', wagtail.images.blocks.ImageChooserBlock(required=False)), ('bouton', wagtail.blocks.StructBlock([('texte', wagtail.blocks.CharBlock(required=True)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('url_externe', wagtail.blocks.URLBlock(required=False)), ('style', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primaire'), ('secondary', 'Secondaire'), ('outline', 'Contour'), ('ghost', 'Transparent')]))])), ('style', wagtail.blocks.ChoiceBlock(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('primary', 'Couleur primaire'), ('gradient', 'Dégradé')]))]))], blank=True)),
                ('horaires', wagtail.fields.RichTextField(blank=True)),
                ('lieu', models.CharField(blank=True, max_length=300)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_telephone', models.CharField(blank=True, max_length=50)),
                ('documents_requis', wagtail.fields.RichTextField(blank=True, verbose_name='Documents requis')),
                ('image_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee')),
            ],
            options={
                'verbose_name': 'Page service',
                'verbose_name_plural': 'Pages services',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('fonction', models.CharField(blank=True, max_length=200)),
                ('temoignage', models.TextField()),
                ('note', models.PositiveIntegerField(default=5, help_text='Note de 1 à 5')),
                ('publie', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.imagepersonnalisee')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ImagePersonnaliseeRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='cms.imagepersonnalisee')),
            ],
            options={
                'unique_together': {('image', 'filter_spec', 'focal_point_key')},
            },
            bases=(wagtail.images.models.ImageFileMixin, models.Model),
        ),
    ]
